version: '3.8'

services:
  backend:
    build: ./Backend
    ports:
      - "8000:8000"
    environment:
      - DECRYPT_KEY=CdBFncAwq7v1nqrrmSznOt-GKBXtN55ZtbOT6wWQtck=

  frontend:
    build: ./Frontend/askdoc
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend