version: '3.8'

services:
  backend:
    build: ./Backend
    ports:
      - "8000:8000"
    environment:
      - DECRYPT_KEY=ABRpFgRePJ1ti9FXwxPpTb-yquaI4QziRNZ2wuv_dHg=

  frontend:
    build: ./Frontend/askdoc
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend