name: CI/CD to Azure VM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: "172.190.112.201"
          username: "omgdocindia"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo chown -R $(whoami) /home/omgdocindia/Askdoc
            cd /home/omgdocindia/Askdoc
            git pull origin master
            docker-compose down
            docker-compose up -d --build
